// Generated by gencpp from file beginner_tutorials/Capital.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_CAPITAL_H
#define BEGINNER_TUTORIALS_MESSAGE_CAPITAL_H

#include <ros/service_traits.h>


#include <beginner_tutorials/CapitalRequest.h>
#include <beginner_tutorials/CapitalResponse.h>


namespace beginner_tutorials
{

struct Capital
{

typedef CapitalRequest Request;
typedef CapitalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Capital
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Capital > {
  static const char* value()
  {
    return "a5ee83af03ea54aa1ccd872ec98f7439";
  }

  static const char* value(const ::beginner_tutorials::Capital&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Capital > {
  static const char* value()
  {
    return "beginner_tutorials/Capital";
  }

  static const char* value(const ::beginner_tutorials::Capital&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::CapitalRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Capital > 
template<>
struct MD5Sum< ::beginner_tutorials::CapitalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Capital >::value();
  }
  static const char* value(const ::beginner_tutorials::CapitalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::CapitalRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Capital > 
template<>
struct DataType< ::beginner_tutorials::CapitalRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Capital >::value();
  }
  static const char* value(const ::beginner_tutorials::CapitalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::CapitalResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Capital > 
template<>
struct MD5Sum< ::beginner_tutorials::CapitalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Capital >::value();
  }
  static const char* value(const ::beginner_tutorials::CapitalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::CapitalResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Capital > 
template<>
struct DataType< ::beginner_tutorials::CapitalResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Capital >::value();
  }
  static const char* value(const ::beginner_tutorials::CapitalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_CAPITAL_H
