// Generated by gencpp from file beginner_tutorials/ParseFileResult.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_PARSEFILERESULT_H
#define BEGINNER_TUTORIALS_MESSAGE_PARSEFILERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ParseFileResult_
{
  typedef ParseFileResult_<ContainerAllocator> Type;

  ParseFileResult_()
    : frame()  {
    }
  ParseFileResult_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> const> ConstPtr;

}; // struct ParseFileResult_

typedef ::beginner_tutorials::ParseFileResult_<std::allocator<void> > ParseFileResult;

typedef boost::shared_ptr< ::beginner_tutorials::ParseFileResult > ParseFileResultPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ParseFileResult const> ParseFileResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ParseFileResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/samveed/Music/catkin_ws/devel/share/beginner_tutorials/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b55303c7ce58fb6c0ed76cd13a628a1c";
  }

  static const char* value(const ::beginner_tutorials::ParseFileResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb55303c7ce58fb6cULL;
  static const uint64_t static_value2 = 0x0ed76cd13a628a1cULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ParseFileResult";
  }

  static const char* value(const ::beginner_tutorials::ParseFileResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result\n\
string[] frame\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::ParseFileResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParseFileResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ParseFileResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ParseFileResult_<ContainerAllocator>& v)
  {
    s << indent << "frame[]" << std::endl;
    for (size_t i = 0; i < v.frame.size(); ++i)
    {
      s << indent << "  frame[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_PARSEFILERESULT_H
