// Generated by gencpp from file beginner_tutorials/ParseFileFeedback.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_PARSEFILEFEEDBACK_H
#define BEGINNER_TUTORIALS_MESSAGE_PARSEFILEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ParseFileFeedback_
{
  typedef ParseFileFeedback_<ContainerAllocator> Type;

  ParseFileFeedback_()
    : last_frame()  {
    }
  ParseFileFeedback_(const ContainerAllocator& _alloc)
    : last_frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_frame_type;
  _last_frame_type last_frame;





  typedef boost::shared_ptr< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ParseFileFeedback_

typedef ::beginner_tutorials::ParseFileFeedback_<std::allocator<void> > ParseFileFeedback;

typedef boost::shared_ptr< ::beginner_tutorials::ParseFileFeedback > ParseFileFeedbackPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ParseFileFeedback const> ParseFileFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/samveed/Music/catkin_ws/devel/share/beginner_tutorials/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10ec73c818e9fd2433ddd84137843e1c";
  }

  static const char* value(const ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10ec73c818e9fd24ULL;
  static const uint64_t static_value2 = 0x33ddd84137843e1cULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ParseFileFeedback";
  }

  static const char* value(const ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
string last_frame\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.last_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParseFileFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ParseFileFeedback_<ContainerAllocator>& v)
  {
    s << indent << "last_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_PARSEFILEFEEDBACK_H
