// Auto-generated. Do not edit!

// (in-package beginner_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ParseFileFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.last_frame = null;
    }
    else {
      if (initObj.hasOwnProperty('last_frame')) {
        this.last_frame = initObj.last_frame
      }
      else {
        this.last_frame = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ParseFileFeedback
    // Serialize message field [last_frame]
    bufferOffset = _serializer.string(obj.last_frame, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ParseFileFeedback
    let len;
    let data = new ParseFileFeedback(null);
    // Deserialize message field [last_frame]
    data.last_frame = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.last_frame.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'beginner_tutorials/ParseFileFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '10ec73c818e9fd2433ddd84137843e1c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    string last_frame
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ParseFileFeedback(null);
    if (msg.last_frame !== undefined) {
      resolved.last_frame = msg.last_frame;
    }
    else {
      resolved.last_frame = ''
    }

    return resolved;
    }
};

module.exports = ParseFileFeedback;
