(cl:defpackage beginner_tutorials-msg
  (:use )
  (:export
   "<PARSEFILEACTION>"
   "PARSEFILEACTION"
   "<PARSEFILEACTIONFEEDBACK>"
   "PARSEFILEACTIONFEEDBACK"
   "<PARSEFILEACTIONGOAL>"
   "PARSEFILEACTIONGOAL"
   "<PARSEFILEACTIONRESULT>"
   "PARSEFILEACTIONRESULT"
   "<PARSEFILEFEEDBACK>"
   "PARSEFILEFEEDBACK"
   "<PARSEFILEGOAL>"
   "PARSEFILEGOAL"
   "<PARSEFILERESULT>"
   "PARSEFILERESULT"
  ))

