; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude ParseFileResult.msg.html

(cl:defclass <ParseFileResult> (roslisp-msg-protocol:ros-message)
  ((frame
    :reader frame
    :initarg :frame
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass ParseFileResult (<ParseFileResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ParseFileResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ParseFileResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<ParseFileResult> is deprecated: use beginner_tutorials-msg:ParseFileResult instead.")))

(cl:ensure-generic-function 'frame-val :lambda-list '(m))
(cl:defmethod frame-val ((m <ParseFileResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:frame-val is deprecated.  Use beginner_tutorials-msg:frame instead.")
  (frame m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ParseFileResult>) ostream)
  "Serializes a message object of type '<ParseFileResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'frame))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'frame))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ParseFileResult>) istream)
  "Deserializes a message object of type '<ParseFileResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'frame) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'frame)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ParseFileResult>)))
  "Returns string type for a message object of type '<ParseFileResult>"
  "beginner_tutorials/ParseFileResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ParseFileResult)))
  "Returns string type for a message object of type 'ParseFileResult"
  "beginner_tutorials/ParseFileResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ParseFileResult>)))
  "Returns md5sum for a message object of type '<ParseFileResult>"
  "b55303c7ce58fb6c0ed76cd13a628a1c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ParseFileResult)))
  "Returns md5sum for a message object of type 'ParseFileResult"
  "b55303c7ce58fb6c0ed76cd13a628a1c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ParseFileResult>)))
  "Returns full string definition for message of type '<ParseFileResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string[] frame~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ParseFileResult)))
  "Returns full string definition for message of type 'ParseFileResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string[] frame~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ParseFileResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'frame) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ParseFileResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ParseFileResult
    (cl:cons ':frame (frame msg))
))
