; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude ParseFileGoal.msg.html

(cl:defclass <ParseFileGoal> (roslisp-msg-protocol:ros-message)
  ((index
    :reader index
    :initarg :index
    :type cl:integer
    :initform 0))
)

(cl:defclass ParseFileGoal (<ParseFileGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ParseFileGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ParseFileGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<ParseFileGoal> is deprecated: use beginner_tutorials-msg:ParseFileGoal instead.")))

(cl:ensure-generic-function 'index-val :lambda-list '(m))
(cl:defmethod index-val ((m <ParseFileGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:index-val is deprecated.  Use beginner_tutorials-msg:index instead.")
  (index m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ParseFileGoal>) ostream)
  "Serializes a message object of type '<ParseFileGoal>"
  (cl:let* ((signed (cl:slot-value msg 'index)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ParseFileGoal>) istream)
  "Deserializes a message object of type '<ParseFileGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'index) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ParseFileGoal>)))
  "Returns string type for a message object of type '<ParseFileGoal>"
  "beginner_tutorials/ParseFileGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ParseFileGoal)))
  "Returns string type for a message object of type 'ParseFileGoal"
  "beginner_tutorials/ParseFileGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ParseFileGoal>)))
  "Returns md5sum for a message object of type '<ParseFileGoal>"
  "483eea06cdc3e559421ee31116d0f3b9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ParseFileGoal)))
  "Returns md5sum for a message object of type 'ParseFileGoal"
  "483eea06cdc3e559421ee31116d0f3b9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ParseFileGoal>)))
  "Returns full string definition for message of type '<ParseFileGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 index~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ParseFileGoal)))
  "Returns full string definition for message of type 'ParseFileGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 index~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ParseFileGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ParseFileGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ParseFileGoal
    (cl:cons ':index (index msg))
))
